<?php
namespace rpc;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class DataResult
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'Code',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        2 => array(
            'var' => 'Msg',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'Gift',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\rpc\DataGiftPrize',
        ),
    );

    /**
     * @var int
     */
    public $Code = null;
    /**
     * @var string
     */
    public $Msg = null;
    /**
     * @var \rpc\DataGiftPrize
     */
    public $Gift = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['Code'])) {
                $this->Code = $vals['Code'];
            }
            if (isset($vals['Msg'])) {
                $this->Msg = $vals['Msg'];
            }
            if (isset($vals['Gift'])) {
                $this->Gift = $vals['Gift'];
            }
        }
    }

    public function getName()
    {
        return 'DataResult';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->Code);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->Msg);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRUCT) {
                        $this->Gift = new \rpc\DataGiftPrize();
                        $xfer += $this->Gift->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('DataResult');
        if ($this->Code !== null) {
            $xfer += $output->writeFieldBegin('Code', TType::I64, 1);
            $xfer += $output->writeI64($this->Code);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Msg !== null) {
            $xfer += $output->writeFieldBegin('Msg', TType::STRING, 2);
            $xfer += $output->writeString($this->Msg);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Gift !== null) {
            if (!is_object($this->Gift)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('Gift', TType::STRUCT, 3);
            $xfer += $this->Gift->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
